name: test

on:
  workflow_dispatch:
    inputs:
      success:
        description: "true=正常退出，false=错误退出"
        required: true
        default: "1"
        type: choice
        options:
          - "1"
          - "0"
          - "true"
          - "false"
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
      enableFeatureX:
        description: 'Enable feature X'
        required: false
        type: 'boolean'
        default: false

jobs:
  my-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test"  >> $GITHUB_STEP_SUMMARY
      - name: Adding markdown 
        run: echo '### Hello world! 🚀' >> $GITHUB_STEP_SUMMARY
  my-test2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test"
      - name: Adding markdown
        run: echo '### Welcome to Gitea Summaries! 🚀' >> $GITHUB_STEP_SUMMARY
